## This Plugin was written by Robert Kratz on 11. Mai 2021
## You need help with setting up the Plugin? Check out my Discord: https://link.rjks.us/support

enabled: false
database: false

## Database Structure

mysql:
  user: 'root'
  password: ''
  host: 'localhost'
  database: 'game'
  port: '3306'

## Here you can plug in your own coin system if you have one, just user the same database
## and define your uuid row and coins row and the plugin will use your coin System
## NOTICE: ONCE DEFINED, WE DO NOT RECOMMEND CHANGING THESE VALUES!

coins:
  table: 'game_coins'
  uuid-row: 'uuid'
  coins-row: 'coins'

stats:
  table: 'game_stats'
  uuid-row: 'uuid'
  kills-row: 'kills'
  deaths-row: 'deaths'

## Rank System Config

enable-rank-system: false
enable-tab-rank: false
enable-chat-rank: false
display-effect-on-player: false
display-effect-on-top-while-sneaking: false

## Ingame Config

enable-player-joins-message: true
enable-player-leaves-message: true

game-action-bar-enabled: true
show-score-board: true
hearts-when-join: 20.0

## Sound could also be > none <, then no sound will be played
## Regular Chest for regular-loot
regular-chest-type: "CHEST"
regular-chest-open-sound: "CLICK"
regular-chest-duration-until-respawn: 5

## Regular Chest for legendary-loot
legendary-chest-type: "ENDER_CHEST"
legendary-chest-open-sound: "CLICK"
legendary-chest-duration-until-respawn: 10


## Regular Chest for legendary-loot
special-chest-type: "BEACON"
special-chest-open-sound: "CLICK"
special-chest-duration-until-respawn: 20

## Kill Event, to use stats and coins mysql must be enabled on the server
enable-coins-system: true
enable-stats-system: true

killer-coins-on-kill: 5
player-lose-coins-on-death: 2

killstreak-bonus-coins: 5

kill-streak-bonus-coins:
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20

kill-streak-broadcast:
  - 3
  - 5
  - 10
  - 15
  - 20
  - 25
  - 30
  - 35
  - 40
  - 45
  - 50
  - 100
  - 150
  - 200
  - 500
  - 1000

## This requires a minimum of 2 maps in the cache
map-change-counter-enabled: true
map-change-counter: 500
map-change-counter-allow-two-maps-in-a-row: false
enable-spawn-protection: true
spawn-protection-duration: 5

map-change-announcement-in-chat:
  - 500
  - 250
  - 100
  - 50
  - 30
  - 10
  - 5
  - 3
  - 2
  - 1

## If a Player executes the command /skip, the countdown will be set to the set number below
map-skip-countdown-to: 5
map-skip-countdown-possible-only-at-second: 100

permissions:
  operator: system.game.operator
  skip: system.game.cmd.skip
  always-skip: system.game.cmd.skip.always
  forcemap: system.game.cmd.forcemap

## Here you can configure the loot for a legendary chest, if you want to lower the chance of an item, just add more of other items to the list

regular-items:
  - ==: org.bukkit.inventory.ItemStack
    type: STONE_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Stone Sword'
  - ==: org.bukkit.inventory.ItemStack
    type: GOLD_AXE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Gold Axe'
  - ==: org.bukkit.inventory.ItemStack
    type: GOLD_BOOTS
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Gold Boots'
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&bDiamond Sword'
  - ==: org.bukkit.inventory.ItemStack
    type: ARROW
    amount: 4
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Munition'
  - ==: org.bukkit.inventory.ItemStack
    type: BOW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Bow'
      enchants:
        ARROW_DAMAGE: 2
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&bDiamond Sword'
  - ==: org.bukkit.inventory.ItemStack
    type: COOKED_BEEF
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Beef'
  - ==: org.bukkit.inventory.ItemStack
    type: COOKED_BEEF
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Beef'
  - ==: org.bukkit.inventory.ItemStack
    type: COOKED_BEEF
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Beef'
  - ==: org.bukkit.inventory.ItemStack
    type: COOKED_BEEF
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Beef'

## Here you can configure the loot for a legendary chest, if you want to lower the chance of an item, just add more of other items to the list

legendary-items:
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_CHESTPLATE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Stone Sword'
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_CHESTPLATE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Gold Axe'
  - ==: org.bukkit.inventory.ItemStack
    type: GOLD_BOOTS
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Gold Boots'
  - ==: org.bukkit.inventory.ItemStack
    type: ARROW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&bDiamond Sword'
  - ==: org.bukkit.inventory.ItemStack
    type: ARROW
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Munition'
  - ==: org.bukkit.inventory.ItemStack
    type: BOW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Bow'
      enchants:
        ARROW_DAMAGE: 2
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&bDiamond Sword'
  - ==: org.bukkit.inventory.ItemStack
    type: COOKED_BEEF
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Beef'
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_SWORD
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Beef'
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_CHESTPLATE
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Beef'
  - ==: org.bukkit.inventory.ItemStack
    type: COOKED_BEEF
    amount: 16
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Beef'

## Here you can configure the effects for a spectial chest, if you want to lower the chance of an item, just add more of other items to the list
## You can find a list of all id's of the PotionEffects here: https://mcreator.net/wiki/potion-effect-ids
## The duration is in ticks -> 20 ticks equals 1 second

special-effects:
  - ==: PotionEffect
    effect: 1
    duration: 600
    amplifier: 2
    ambient: true
    has-particles: true
  - ==: PotionEffect
    effect: 8
    duration: 600
    amplifier: 2
    ambient: true
    has-particles: true
  - ==: PotionEffect
    effect: 23
    duration: 600
    amplifier: 1
    ambient: true
    has-particles: true